version: '3'

services:
  my-spring-boot-service:
    image: myimage:1.0
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"  # Map Prometheus port
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
