version: '3'

services:
  my-spring-boot-service:
    container_name: app
    image: gpd:latest
    ports:
      - "8080:8080"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"  # Map Prometheus port
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - my-spring-boot-service
