global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'grocery-product-detector'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080'] # Replace with your application's host and port
